# Generated by Django 4.2 on 2023-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='password',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
