# Generated by Django 4.2 on 2023-04-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_email_studentsdata_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='photo_coordinates',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
